CREATE DATABASE VIZLIFE;

CREATE TABLE GOAL (
	ID INT PRIMARY KEY,
	NAME VARCHAR(25),
	DESCRIPTION TEXT,
	USER_ID INT REFERENCES USER_INFO(ID),
	METRIC1_ID INT REFERENCES METRIC_INFO(ID),
	METRIC2_ID INT REFERENCES METRIC_INFO(ID),
	METRIC3_ID INT REFERENCES METRIC_INFO(ID),
	METRIC1_DVAL NUMERIC(3,2),
	METRIC2_DVAL NUMERIC(3,2),
	METRIC3_DVAL NUMERIC(3,2)
);

CREATE TABLE METRIC_INFO(
	ID INT PRIMARY KEY,
    DESCRIPTION TEXT
);

CREATE TABLE METRIC(
	METRIC_ID INT REFERENCES METRIC_INFO(ID),
    USER_ID INT REFERENCES USER_INFO(ID),
    DATE_STAMP DATE,
    METRIC_VAL NUMERIC(3,2)
);

CREATE TABLE USER_INFO (
	ID INT PRIMARY KEY,
    DEVICE_ID VARCHAR(50),
    NAME VARCHAR(35)
);